In [1]:
import numpy as np
from icecream import ic

In [2]:
def calc_quadratic_gradient(Q, b, point):
    return Q@point - b

def conjugate_gradient_algorithm_quadratic(Q, b, initial_point, threshold = 1e-3, maxiter = 10):
    conjugate_list = []
    gradient_list = []
    point_list = []
    alpha_list = []
    beta_list = []
    point = initial_point
    
    i = 0
    
    point = initial_point
    point_list.append(point)
    gradient = calc_quadratic_gradient(Q, b, point)
    if np.linalg.norm(gradient) < threshold:
        print("finish")
        return
    else:
        conjugate = - gradient
        conjugate_list.append(conjugate)
        
    while True:
        i +=1
        alpha = - (gradient.T@conjugate)/(conjugate.T@Q@conjugate)
        alpha_list.append(alpha)
        
        next_point = point + alpha * conjugate
        next_gradient = calc_quadratic_gradient(Q, b, next_point)
        point_list.append(next_point)
        gradient_list.append(next_gradient)
        
        if (np.linalg.norm(next_gradient) < threshold) or (i>maxiter):
            print("%d iterations : finish"%i)
            ic(point_list, gradient_list, conjugate_list, alpha_list, beta_list)
            return 
        
        beta = (next_gradient.T@Q@conjugate)/(conjugate.T@Q@conjugate)
        beta_list.append(beta)
        
        next_conjugate = -next_gradient + beta * conjugate

        gradient = next_gradient
        conjugate = next_conjugate
        point = next_point
        
        
        conjugate_list.append(conjugate)
        

# 10.10

In [3]:
Q = np.array([[5,2],[2,1]])
b = np.array([[3,1]]).T
x = np.array([[0,0]]).T

In [4]:
conjugate_gradient_algorithm_quadratic(Q, b, x)

ic| point_list: [array([[0],
                       [0]]),
                 array([[0.51724138],
                       [0.17241379]]),
                 array([[ 1.],
                       [-1.]])]
    gradient_list: [array([[-0.06896552],
                          [ 0.20689655]]),
                    array([[8.8817842e-16],
                          [4.4408921e-16]])]
    conjugate_list: [array([[3],
                           [1]]), array([[ 0.08323424],
                           [-0.20214031]])]
    alpha_list: [array([[0.17241379]]), array([[5.8]])]
    beta_list: [array([[0.00475624]])]


2 iterations : finish
